version: '3.3'
services:
    traefik:
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - $PWD/traefik.toml:/traefik.toml
            - $PWD/acme.json:/acme.json
        ports:
            - 80:80
            - 443:443
        container_name: traefik
        image: traefik:1.7.2-alpine
        labels:
            - traefik.frontend.rule=Host:traefik.itpolice.ru
            - traefik.port=8080
        networks:
            - web

networks:
    web:
        external: true
